name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  cloud_firestore: ^2.5.2
  modal_progress_hud: ^0.1.3
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
